version: "2.4"

services:
  pipeline-controller:
    image: us-docker.pkg.dev/cloud-build-fhir/fhir-analytics/main:latest
    container_name: ihe-pipeline-controller
    restart: unless-stopped
    volumes:
      - ${PIPELINE_CONFIG}:/app/config:ro
      - ${DWH_ROOT}:/dwh
    environment:
      - JAVA_OPTS=$JAVA_OPTS
    ports:
      - '8090:8080'
    networks:
      - cloudbuild
      - default
    depends_on:
      spark:
        condition: service_healthy

  spark:
    image: docker.io/bitnami/spark:3.3
    container_name: ihe-spark-thriftserver
    restart: unless-stopped
    command:
      - sbin/start-thriftserver.sh
      - --driver-memory
      # You may need to increase this if your queries/data are too large.
      - 5g
    environment:
      - HIVE_SERVER2_THRIFT_PORT=10000
    ports:
      - '10001:10000'
      - '4041:4040'
    volumes:
      - ${DWH_ROOT}:/dwh
      # NON-EMBEDDED METASTORE CONFIG:
      # If you want to persist the Metastore data, e.g., table and view
      # definitions, you can use an external database by adjusting hive-site.xml
      #- ./hive-site_example.xml:/opt/bitnami/spark/conf/hive-site.xml
      # Note to use an external DB, you need to provide its driver jar too:
      #- ./postgresql-42.6.0.jar:/opt/bitnami/spark/jars/postgresql-42.6.0.jar
      - spark_vol_single:/opt/bitnami/spark
    networks:
      - cloudbuild
      - default
    healthcheck:
      test: beeline help || exit 1
      interval: 10s
      retries: 10
      start_period: 5s
      timeout: 60s


volumes:
  spark_vol_single:

networks:
  cloudbuild:
    name: cloudbuild