version: "3.8"


services:

  hapi-postgres:
      image: postgres:14.1-alpine
      container_name: ihe_hapi_postgres
      environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=fhirdb
      ports:
          - '5433:5432'
      volumes:
          - ihe-hapi_db_vol:/var/lib/postgresql/data
      networks:
          - lan

  hapi-server:
      image: "hapiproject/hapi:v6.6.0"
      container_name: ihe_hapi_server
      ports:
          - "8090:8080"
      volumes:
          - ./hapi-config:/custom/config/hapi
      environment:
          SPRING_CONFIG_LOCATION: 'file:///custom/config/hapi/hapi-application.yml'
      networks:
          - lan
      depends_on:
          - hapi-postgres

networks:
  lan:
    name: impilo
  opencr:
    name: opencr
  hapi-fhir:
    name: hapi-fhir_public
  public:
    name: openhim_public
  kafka_public:
    name: kafka_public

volumes:
    ihe-hapi_db_vol:
        name: ihe-hapi_db_vol
        driver: local
