version: "3.8"


services:

  hapi-postgres:
      image: postgres:14.1-alpine
      container_name: ihe_hapi_postgres
      restart: unless-stopped
      environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=fhirdb
      ports:
          - '5433:5432'
      volumes:
          - ihe-hapi_db_vol:/var/lib/postgresql/data
      networks:
          - mini-hie

  hapi-server:
      image: "hapiproject/hapi:v6.6.0"
      container_name: ihe_hapi_server
      restart: unless-stopped
      volumes:
          - ./hapi-config:/custom/config/hapi
      environment:
          SPRING_CONFIG_LOCATION: 'file:///custom/config/hapi/hapi-application.yml'
      networks:
          - mini-hie
      depends_on:
          - hapi-postgres

networks:
  mini-hie:
    name: mini-hie

volumes:
    ihe-hapi_db_vol:
        name: ihe-hapi_db_vol
        driver: local
