version: '3'
services:
  ihe-haproxy:
    image: haproxy:1.7
    container_name: ihe_haproxy
    restart: unless-stopped
    volumes:
      - ./haproxy-config:/usr/local/etc/haproxy:ro
    ports:
      - '9199:9199'
      - '8888:8888'
      - '9198:9198'
    networks:
      - cloudbuild

networks:
  cloudbuild:
    name: cloudbuild