version: "3.8"


services:

  amqp:
    image: rabbitmq:management-alpine
    container_name: ihe-impilo-amqp
    restart: unless-stopped
    volumes:
      - ../data/amqp:/var/lib/rabbitmq/mnesia
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - cloudbuild

  consul:
    image: consul:0.9.3
    container_name: ihe-impilo-consul
    restart: unless-stopped
    command: consul agent -dev -ui -client 0.0.0.0
    networks:
      - cloudbuild

  config:
    image: jhipster/consul-config-loader:v0.2.2
    container_name: ihe-impilo-config
    restart: unless-stopped
    volumes:
      - ./impilo-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
    networks:
      - cloudbuild

  mysql:
    image: mysql:5.7.20
    container_name: ihe-impilo-mysql
    restart: unless-stopped
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./data/backup:/opt
    environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=mrs
    command: mysqld --log-bin --server-id=184054 --log-bin=b1028c835df2-bin --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --max_allowed_packet=30000000
    networks:
        - cloudbuild
 
  server:
    image: mohcc/mrs:${VERSION}
    container_name: ihe-impilo-server
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:8080
    environment:
      - SPRING_PROFILES_ACTIVE=$PROFILE
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - APPLICATION_SITEID=${SITE_ID}
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    networks:
      - cloudbuild
    depends_on:
      - mysql
      - amqp

  deduplication:
    image: tinashebutsa/deduplication:1.5
    container_name: ihe-impilo-deduplication
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=mysql
      - MYSQL_PASSWORD=
      - amqpserver=amqp
      - PYTHONUNBUFFERED=1
    networks:
      - cloudbuild
    restart: unless-stopped
    depends_on:
      - mysql
      - amqp

networks:
  cloudbuild:
    name: cloudbuild