version: "3.8"


services:

  impilo-amqp:
    image: rabbitmq:management-alpine
    container_name: ihe-impilo-amqp
    restart: always
    volumes:
      - ../data/amqp:/var/lib/rabbitmq/mnesia
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - lan

  impilo-consul:
    image: consul:0.9.3
    container_name: ihe-impilo-consul
    restart: always
    command: consul agent -dev -ui -client 0.0.0.0
    networks:
      - lan

  impilo-config:
    image: jhipster/consul-config-loader:v0.2.2
    container_name: ihe-impilo-config
    restart: always
    volumes:
      - ./impilo-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=impilo-consul
      - CONSUL_PORT=8500
    networks:
      - lan

  impilo-mysql:
    image: mysql:5.7.20
    container_name: ihe-impilo-mysql
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./data/backup:/opt
    environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=mrs
    ports:
            - 3307:3306
    command: mysqld --log-bin --server-id=184054 --log-bin=b1028c835df2-bin --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --max_allowed_packet=30000000
    networks:
        - lan
 
  impilo-server:
    image: mohcc/mrs:${VERSION}
    container_name: ihe-impilo-server
    restart: always
    ports:
      - ${SERVER_PORT}:8080
    environment:
      - SPRING_PROFILES_ACTIVE=$PROFILE
      - SPRING_CLOUD_CONSUL_HOST=impilo-consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - APPLICATION_SITEID=${SITE_ID}
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    networks:
      - lan
    depends_on:
      - impilo-mysql
      - impilo-amqp

  impilo-deduplication:
    image: tinashebutsa/deduplication:1.5
    container_name: ihe-impilo-deduplication
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=impilo-mysql
      - MYSQL_PASSWORD=
      - amqpserver=impilo-amqp
      - PYTHONUNBUFFERED=1
    ports:
      - 3000:3000
    networks:
      - lan
    restart: always
    depends_on:
      - impilo-mysql
      - impilo-amqp

networks:
  lan:
    name: impilo
  opencr:
    name: opencr
  hapi-fhir:
    name: hapi-fhir_public
  public:
    name: openhim_public
  kafka_public:
    name: kafka_public