version: '2.4'

services:
  openldap:
    container_name: ihe-ldap
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=hive,user01,user02
      - LDAP_PASSWORDS=hive,password1,password2
      - LDAP_ROOT=dc=mohcc,dc=gov,dc=zw
      - LDAP_ADMIN_DN=cn=admin,dc=mohcc,dc=gov,dc=zw
    networks:
      - cloudbuild
    volumes:
      - 'openldap_data:/bitnami/openldap'
volumes:
  openldap_data:
    driver: local

networks:
  cloudbuild:
    name: cloudbuild