version: "2.4"


services:
  mrs_debezium:
    image: mohcc/mrs-debezium:2.0.5
    container_name: ihe_mrs_debezium
    restart: unless-stopped
    environment:
      - DATABASE_HOSTNAME=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=debezium
      - DATABASE_PASSWORD=pass123
      - DATABASE_SERVERNAME=ZW000B04
      - DATABASE_HISTORY_FILENAME=/tmp/history-file-1.dat
      - OFFSET_STORAGE_FILENAME=/tmp/offset.dat
      - HIE_USERNAME=test
      - HIE_PASSWORD=test1234
      - HIE_CR_URL=http://server:8080/fhir/
      - HIE_CR_ENABLED=false
      - HIE_SHR_URL=http://openhim-core:5001/SHR/fhir/
      - HIE_SHR_ENABLED=true
      - KAFKA_BROKERS=kafka-01:9092
      - KAFKA_ENABLED=false
    networks:
      - cloudbuild

networks:
  cloudbuild:
    name: cloudbuild


    


    