version : '3'
services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./local/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./local/certs:/etc/nginx/certs/
      - ./local/conf/.htpasswd:/etc/nginx/.htpasswd
    networks:
      - cloudbuild

networks:
  cloudbuild:
    name: cloudbuild