version: '2.4'

services:
  superset:
    image: apache/superset
    container_name: superset
    restart: unless-stopped
    ports:
      - "8089:8088"
    depends_on:
      - superset_db
      - superset_redis
    environment:
      - SUPERSET_DB_URI=postgresql+psycopg2://superset:superset@superset_db/superset
      - SUPERSET_LOAD_EXAMPLES=yes
      - REDIS_URL=redis://superset_redis:6379/0
      - SUPERSET_SECRET_KEY=uEsfk9HNnscCpW2doB2ZBs0Q9LysPfMSNV5/s3t6XKtGL6qu+4OlHuZn
      # - SUPERSET_CONFIG_PATH=./superset_config.py  # Explicitly setting PYTHONPATH
    volumes:
      - superset_home:/app/superset_home
    # command: ["bash", "-c", "pip install pyhive thrift sasl thrift-sasl && superset run -p 8088 --with-threads --reload --debugger"]

  superset_db:
    image: postgres:13
    container_name: superset_db
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
    volumes:
      - superset_db_home:/var/lib/postgresql/data

  superset_redis:
    image: redis:latest
    container_name: superset_redis
    volumes:
      - superset_redis_home:/data

volumes:
  superset_home:
  superset_db_home:
  superset_redis_home:

networks:
  default:
    external:
      name: cloudbuild
